topics:
  - /agt/sensors/lidar/custom
  - /agt/sensors/imu/data
  - /agt/sensors/camera/front/image_raw
  - /agt/sensors/camera/front/camera_info
  - /agt/sensors/camera/front/status
  - /agt/sensors/gnss/fix
  - /agt/sensors/gnss/velocity
  - /agt/sensors/gnss/time_reference
  - /agt/sensors/gnss/status
  - /agt/sensors/sync/status
  - /diagnostics
  - /tf
  - /tf_static
